name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check Formatting (Prettier)
        run: npm run lint:check

      - name: Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run test:unit

  e2e-postgres:
    name: E2E Tests (PostgreSQL)
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build
          npm link

      - name: Install PostgreSQL Client Tools
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Start PostgreSQL Database (Docker)
        run: npm run test:e2e:pgsql:up

      - name: Run E2E Tests for PostgreSQL
        run: npm run test:e2e:pgsql

      - name: Teardown Database
        if: always() # Garante que os containers morram mesmo se o teste falhar
        run: npm run test:e2e:pgsql:down

  e2e-mysql:
    name: E2E Tests (MySQL)
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies & Build
        run: |
          npm ci
          npm run build
          npm link

      - name: Install MySQL Client Tools
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Start MySQL Database (Docker)
        run: npm run test:e2e:mysql:up

      - name: Run E2E Tests for MySQL
        run: npm run test:e2e:mysql

      - name: Teardown Database
        if: always()
        run: npm run test:e2e:mysql:down
